# Generated by Django 4.0.2 on 2022-03-15 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uahelp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2022, 3, 15)),
        ),
        migrations.AddField(
            model_name='post',
            name='is_verificated',
            field=models.BooleanField(default=False),
        ),
    ]
