# Generated by Django 4.0.2 on 2022-03-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uahelp_app', '0009_alter_profile_account_type_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
